const Verbs = [
  { base: "be", pastSimple: "was/were", pastParticiple: "been", definition: "exist", example: "\"there are no easy answers\"" },
  { base: "beat", pastSimple: "beat", pastParticiple: "beaten",
    definition: "strike (a person or an animal) repeatedly and violently so as to hurt or injure them, typically with an implement such as a club or whip.",
    example: "\"if we were caught we were beaten\"" },
  { base: "become", pastSimple: "became", pastParticiple: "become", definition: "begin to be.", example: "\"she became angry and sulked all day\"" },
  { base: "begin", pastSimple: "began", pastParticiple: "begun", definition: "perform or undergo the first part of (an action or activity).",
    example: "Peter had just begun a life sentence for murder\"" },
  { base: "bite", pastSimple: "bit", pastParticiple: "bitten", definition: "(of a person or animal) use the teeth to cut into or through something.",
    example: "\"he bit off a piece of cheese\"" },
  { base: "blow", pastSimple: "blew", pastParticiple: "blown", definition: "(of wind) move creating an air current.",
    example: "\"a cold breeze was blowing in off the sea\"" },
  { base: "break", pastSimple: "broke", pastParticiple: "broken", definition: "separate or cause to separate into pieces as a result of a blow, shock, or strain.",
    example: "\"the branch broke with a loud snap\"" },
  { base: "bring", pastSimple: "brought", pastParticiple: "brought", definition: "take or go with (someone or something) to a place.",
    example: "\"she brought Luke home from hospital\"" },
  { base: "build", pastSimple: "built", pastParticiple: "built", definition: "construct (something) by putting parts or material together.",
    example: "\"the ironworks were built in 1736\"" },
  { base: "buy", pastSimple: "bought", pastParticiple: "bought", definition: "obtain in exchange for payment.", example: "\"she bought six first-class stamps\"" },
  { base: "catch", pastSimple: "caught", pastParticiple: "caught", definition: "intercept and hold (something which has been thrown, propelled, or dropped).",
    example: "\"she threw the bottle into the air and caught it again\"" },
  { base: "choose", pastSimple: "chose", pastParticiple: "chosen",
    definition: "pick out (someone or something) as being the best or most appropriate of two or more alternatives.",
    example: "\"he chose a seat facing the door\"" },
  { base: "come", pastSimple: "came", pastParticiple: "come", definition: "move or travel towards or into a place thought of as near or familiar to the speaker.",
    example: "\"Jessica came into the kitchen\"" },
  { base: "cost", pastSimple: "cost", pastParticiple: "cost",
    definition: "(of an object or action) require the payment of (a specified sum of money) before it can be acquired or done.",
    example: "\"each issue of the magazine costs £1\"" },
  { base: "cut", pastSimple: "cut", pastParticiple: "cut", definition: "make an opening, incision, or wound in (something) with a sharp-edged tool or object.",
    example: "\"he cut his toe on a sharp stone\"" },
  { base: "do", pastSimple: "did", pastParticiple: "done", definition: "perform (an action, the precise nature of which is often unspecified).",
    example: "\"very little work has been done in this field\"" },
  { base: "draw", pastSimple: "drew", pastParticiple: "drawn", definition: "produce (a picture or diagram) by making lines and marks on paper with a pencil, pen, etc.",
    example: "\"he drew a map\"" },
  { base: "drink", pastSimple: "drank", pastParticiple: "drunk", definition: "take (a liquid) into the mouth and swallow.",
    example: "\"we sat by the fire, drinking our tea\"" },
  { base: "drive", pastSimple: "drove", pastParticiple: "driven", definition: "operate and control the direction and speed of a motor vehicle.",
    example: "\"he got into his car and drove off\"" },
  { base: "eat", pastSimple: "ate", pastParticiple: "eaten", definition: "put (food) into the mouth and chew and swallow it.",
    example: "\"he was eating a hot dog\"" },
  { base: "fall", pastSimple: "fell", pastParticiple: "fallen", definition: "move from a higher to a lower level, typically rapidly and without control.",
    example: "\"five inches of snow fell through the night\"" },
  { base: "feel", pastSimple: "felt", pastParticiple: "felt", definition: "be aware of (a person or object) through touching or being touched.",
    example: "\"she felt someone touch her shoulder\"" },
  { base: "fight", pastSimple: "fought", pastParticiple: "fought",
    definition: "take part in a violent struggle involving the exchange of physical blows or the use of weapons.", example: "\"the men were fighting\"" },
  { base: "find", pastSimple: "found", pastParticiple: "found", definition: "discover or perceive by chance or unexpectedly.", 
    example: "\"Lindsey looked up to find Neil watching her\"" },
  { base: "fly", pastSimple: "flew", pastParticiple: "flown", definition: "(of a bird, bat, or insect) move through the air using wings.",
    example: "\"close the door or the moths will fly in\"" },
  { base: "forget", pastSimple: "forgot", pastParticiple: "forgotten", definition: "fail to remember.", example: "\"he had forgotten his lines\"" },
  { base: "get", pastSimple: "got", pastParticiple: "gotten", definition: "come to have (something); receive.", example: "\"I got a letter from him the other day\"" },
  { base: "give", pastSimple: "gave", pastParticiple: "given", definition: "freely transfer the possession of (something) to (someone).",
    example: "\"she gave him presents and clothes\"" },
  { base: "go", pastSimple: "went", pastParticiple: "gone", definition: "move from one place to another; travel.", example: "\"he went out to the shops\"" },
  { base: "grow", pastSimple: "grew", pastParticiple: "grown",
    definition: "(of a living thing) undergo natural development by increasing in size and changing physically.",
    example: "\"he would watch Nick grow to manhood\"" },
  { base: "hang", pastSimple: "hung/hanged", pastParticiple: "hung/hanged", definition: "suspend or be suspended from above with the lower part dangling free.",
    example: "\"that's where people are supposed to hang their washing\"" },
  { base: "have", pastSimple: "had", pastParticiple: "had", definition: "possess, own, or hold.", example: "\"he had a new car and a boat\"" },
  { base: "hear", pastSimple: "heard", pastParticiple: "heard", definition: "perceive with the ear the sound made by (someone or something).",
    example: "\"behind her she could hear men's voices\"" },
  { base: "hide", pastSimple: "hid", pastParticiple: "hidden", definition: "put or keep out of sight.", example: "\"he hid the money in the house\"" },
  { base: "hit", pastSimple: "hit", pastParticiple: "hit", definition: "strike with a hand or an object.", example: "\"he hit the ball with his bat\"" },
  { base: "hold", pastSimple: "held", pastParticiple: "held", definition: "grasp, carry, or support with one's hands.",
    example: "\"she was holding a brown leather suitcase\"" },
  { base: "hurt", pastSimple: "hurt", pastParticiple: "hurt", definition: "cause pain or damage to (someone or something).", example: "\"she hurt her knee\"" },
  { base: "keep", pastSimple: "kept", pastParticiple: "kept", definition: "have or retain possession of.", example: "\"he kept the money in his wallet\"" },
  { base: "know", pastSimple: "knew", pastParticiple: "known", definition: "be aware of through observation, inquiry, or information.",
    example: "\"most people know that CFCs can damage the ozone layer\"" },
  { base: "leave", pastSimple: "left", pastParticiple: "left", definition: "go away from.", example: "\"he left the room\"" },
  { base: "lend", pastSimple: "lent", pastParticiple: "lent", definition: "grant to (someone) the use of (something) on the understanding that it will be returned.",
    example: "\"Stewart asked me to lend him my car\"" },
  { base: "let", pastSimple: "let", pastParticiple: "let", definition: "allow (someone) to do something.", example: "\"she let him go\"" },
  { base: "lie", pastSimple: "lay", pastParticiple: "lain", definition: "be in a horizontal position.", example: "\"he lay on the bed\"" },
  { base: "light", pastSimple: "lit", pastParticiple: "lit", definition: "set fire to (something).", example: "\"he lit the candle\"" },
  { base: "lose", pastSimple: "lost", pastParticiple: "lost", definition: "surrender or misplace (something).", example: "\"she lost her keys\"" },
  { base: "make", pastSimple: "made", pastParticiple: "made", definition: "create or produce (something).", example: "\"he made a cake\"" },
  { base: "mean", pastSimple: "meant", pastParticiple: "meant", definition: "intend (something) when speaking or writing.", example: "\"I didn't mean to hurt you\"" },
  { base: "meet", pastSimple: "met", pastParticiple: "met", definition: "to come together, assemble, encounter, or be introduced",
    example: "\"I met my friend at the park\"" },
  { base: "pay", pastSimple: "paid", pastParticiple: "paid", definition: "give money in exchange for goods or services.", example: "\"I paid for the coffee with cash\"" },
  { base: "put", pastSimple: "put", pastParticiple: "put", definition: "place or position (something) in a particular spot.",  example: "\"I put the book on the shelf\"" },
  { base: "read", pastSimple: "read", pastParticiple: "read", definition: "interpret the meaning of (written or printed matter).", example: "\"I read a book yesterday\"" },	
  { base: "ride", pastSimple: "rode", pastParticiple: "ridden", definition: "travel on or in (a vehicle or animal).", example: "\"I rode my bike to school\"" },
  { base: "ring", pastSimple: "rang", pastParticiple: "rung", definition: "make a sound by striking (a bell or other object).", example: "\"The bell rang at noon\"" },
  { base: "rise", pastSimple: "rose", pastParticiple: "risen", definition: "D", example: "E" },
  { base: "run", pastSimple: "ran", pastParticiple: "run", definition: "D", example: "E" },
  { base: "say", pastSimple: "said", pastParticiple: "said", definition: "D", example: "E" },
  { base: "see", pastSimple: "saw", pastParticiple: "seen", definition: "D", example: "E" },
  { base: "sell", pastSimple: "sold", pastParticiple: "sold", definition: "D", example: "E" },
  { base: "send", pastSimple: "sent", pastParticiple: "sent", definition: "D", example: "E" },
  { base: "set", pastSimple: "set", pastParticiple: "set", definition: "D", example: "E" },
  { base: "shake", pastSimple: "shook", pastParticiple: "shaken", definition: "D", example: "E" },
  { base: "shine", pastSimple: "shone", pastParticiple: "shone", definition: "D", example: "E" },
  { base: "shoot", pastSimple: "shot", pastParticiple: "shot", definition: "D", example: "E" },
  { base: "show", pastSimple: "showed", pastParticiple: "shown", definition: "D", example: "E" },
  { base: "shut", pastSimple: "shut", pastParticiple: "shut", definition: "D", example: "E" },
  { base: "sing", pastSimple: "sang", pastParticiple: "sung", definition: "D", example: "E" },
  { base: "sit", pastSimple: "sat", pastParticiple: "sat", definition: "D", example: "E" },
  { base: "sleep", pastSimple: "slept", pastParticiple: "slept", definition: "D", example: "E" },
  { base: "smell", pastSimple: "smelled", pastParticiple: "smelled", definition: "to perceive odor via the nose, emit an odor, or detect something intuitively",
    example: "I can smell the flowers from here" },
  { base: "speak", pastSimple: "spoke", pastParticiple: "spoken", definition: "D", example: "E" },
  { base: "spend", pastSimple: "spent", pastParticiple: "spent", definition: "D", example: "E" },
  { base: "spell", pastSimple: "spelled", pastParticiple: "spelled", definition: "D", example: "E" },
  { base: "stand", pastSimple: "stood", pastParticiple: "stood", definition: "D", example: "E" },
  { base: "steal", pastSimple: "stole", pastParticiple: "stolen", definition: "D", example: "E" },
  { base: "stick", pastSimple: "stuck", pastParticiple: "stuck", definition: "refers to attaching, adhering, piercing, or putting something in place",
    example: "I need to stick these photos into my album" },
  { base: "still", pastSimple: "stilled", pastParticiple: "stilled", definition: "to make something calm, quiet, or motionless",
    example: "The storm finally stilled down" },
  { base: "sting", pastSimple: "stung", pastParticiple: "stung", definition: "D", example: "E" },
  { base: "swim", pastSimple: "swam", pastParticiple: "swum", definition: "D", example: "E" },
  { base: "take", pastSimple: "took", pastParticiple: "taken", definition: "D", example: "E" },
  { base: "teach", pastSimple: "taught", pastParticiple: "taught", definition: "D", example: "E" },
  { base: "tear", pastSimple: "tore", pastParticiple: "torn", definition: "to pull apart by force, rip, or damage material", example: "I tore the paper into pieces" },
  { base: "tell", pastSimple: "told", pastParticiple: "told", definition: "D", example: "D" },
  { base: "think", pastSimple: "thought", pastParticiple: "thought", definition: "D", example: "E" },
  { base: "throw", pastSimple: "threw", pastParticiple: "thrown", definition: "D", example: "E" },
  { base: "understand", pastSimple: "understood", pastParticiple: "understood", definition: "D", example: "E" },
  { base: "wake", pastSimple: "woke", pastParticiple: "woken", definition: "D", example: "E" },
  { base: "wear", pastSimple: "wore", pastParticiple: "worn", definition: "D", example: "E" },
  { base: "walk", pastSimple: "walked", pastParticiple: "walked", definition: "D", example: "E" },
  { base: "win", pastSimple: "won", pastParticiple: "won", definition: "D", example: "E" },
  { base: "write", pastSimple: "wrote", pastParticiple: "written", definition: "D", example: "E" },
];



// { base: "", pastSimple: "", pastParticiple: "", definition: "", example: "" },