const Verbs = [
  { infinitive: "be", pastSimple: "was/were", pastParticiple: "been", definition: "exist", example: "\"there are no easy answers\"" },
  { infinitive: "beat", pastSimple: "beat", pastParticiple: "beaten",
    definition: "strike (a person or an animal) repeatedly and violently so as to hurt or injure them, typically with an implement such as a club or whip.",
    example: "\"if we were caught we were beaten\"" },
  { infinitive: "become", pastSimple: "became", pastParticiple: "become", definition: "begin to be.", example: "\"she became angry and sulked all day\"" },
  { infinitive: "begin", pastSimple: "began", pastParticiple: "begun", definition: "perform or undergo the first part of (an action or activity).",
    example: "Peter had just begun a life sentence for murder\"" },
  { infinitive: "bite", pastSimple: "bit", pastParticiple: "bitten", definition: "(of a person or animal) use the teeth to cut into or through something.",
    example: "\"he bit off a piece of cheese\"" },
  { infinitive: "blow", pastSimple: "blew", pastParticiple: "blown", definition: "(of wind) move creating an air current.",
    example: "\"a cold breeze was blowing in off the sea\"" },
  { infinitive: "break", pastSimple: "broke", pastParticiple: "broken", definition: "separate or cause to separate into pieces as a result of a blow, shock, or strain.",
    example: "\"the branch broke with a loud snap\"" },
  { infinitive: "bring", pastSimple: "brought", pastParticiple: "brought", definition: "take or go with (someone or something) to a place.",
    example: "\"she brought Luke home from hospital\"" },
  { infinitive: "build", pastSimple: "built", pastParticiple: "built", definition: "construct (something) by putting parts or material together.",
    example: "\"the ironworks were built in 1736\"" },
  { infinitive: "buy", pastSimple: "bought", pastParticiple: "bought", definition: "obtain in exchange for payment.", example: "\"she bought six first-class stamps\"" },
  { infinitive: "catch", pastSimple: "caught", pastParticiple: "caught", definition: "intercept and hold (something which has been thrown, propelled, or dropped).",
    example: "\"she threw the bottle into the air and caught it again\"" },
  { infinitive: "choose", pastSimple: "chose", pastParticiple: "chosen",
    definition: "pick out (someone or something) as being the best or most appropriate of two or more alternatives.",
    example: "\"he chose a seat facing the door\"" },
  { infinitive: "come", pastSimple: "came", pastParticiple: "come", definition: "move or travel towards or into a place thought of as near or familiar to the speaker.",
    example: "\"Jessica came into the kitchen\"" },
  { infinitive: "cost", pastSimple: "cost", pastParticiple: "cost",
    definition: "(of an object or action) require the payment of (a specified sum of money) before it can be acquired or done.",
    example: "\"each issue of the magazine costs £1\"" },
  { infinitive: "cut", pastSimple: "cut", pastParticiple: "cut", definition: "make an opening, incision, or wound in (something) with a sharp-edged tool or object.",
    example: "\"he cut his toe on a sharp stone\"" },
  { infinitive: "do", pastSimple: "did", pastParticiple: "done", definition: "perform (an action, the precise nature of which is often unspecified).",
    example: "\"very little work has been done in this field\"" },
  { infinitive: "draw", pastSimple: "drew", pastParticiple: "drawn", definition: "produce (a picture or diagram) by making lines and marks on paper with a pencil, pen, etc.",
    example: "\"he drew a map\"" },
  { infinitive: "drink", pastSimple: "drank", pastParticiple: "drunk", definition: "take (a liquid) into the mouth and swallow.",
    example: "\"we sat by the fire, drinking our tea\"" },
  { infinitive: "drive", pastSimple: "drove", pastParticiple: "driven", definition: "operate and control the direction and speed of a motor vehicle.",
    example: "\"he got into his car and drove off\"" },
  { infinitive: "eat", pastSimple: "ate", pastParticiple: "eaten", definition: "put (food) into the mouth and chew and swallow it.",
    example: "\"he was eating a hot dog\"" },
  { infinitive: "fall", pastSimple: "fell", pastParticiple: "fallen", definition: "move from a higher to a lower level, typically rapidly and without control.",
    example: "\"five inches of snow fell through the night\"" },
  { infinitive: "feel", pastSimple: "felt", pastParticiple: "felt", definition: "be aware of (a person or object) through touching or being touched.",
    example: "\"she felt someone touch her shoulder\"" },
  { infinitive: "fight", pastSimple: "fought", pastParticiple: "fought",
    definition: "take part in a violent struggle involving the exchange of physical blows or the use of weapons.", example: "\"the men were fighting\"" },
  { infinitive: "find", pastSimple: "found", pastParticiple: "found", definition: "discover or perceive by chance or unexpectedly.", 
    example: "\"Lindsey looked up to find Neil watching her\"" },
  { infinitive: "fly", pastSimple: "flew", pastParticiple: "flown", definition: "(of a bird, bat, or insect) move through the air using wings.",
    example: "\"close the door or the moths will fly in\"" },
  { infinitive: "forget", pastSimple: "forgot", pastParticiple: "forgotten", definition: "fail to remember.", example: "\"he had forgotten his lines\"" },
  { infinitive: "get", pastSimple: "got", pastParticiple: "gotten", definition: "come to have (something); receive.", example: "\"I got a letter from him the other day\"" },
  { infinitive: "give", pastSimple: "gave", pastParticiple: "given", definition: "freely transfer the possession of (something) to (someone).",
    example: "\"she gave him presents and clothes\"" },
  { infinitive: "go", pastSimple: "went", pastParticiple: "gone", definition: "move from one place to another; travel.", example: "\"he went out to the shops\"" },
  { infinitive: "grow", pastSimple: "grew", pastParticiple: "grown",
    definition: "(of a living thing) undergo natural development by increasing in size and changing physically.",
    example: "\"he would watch Nick grow to manhood\"" },
  { infinitive: "hang", pastSimple: "hung/hanged", pastParticiple: "hung/hanged", definition: "suspend or be suspended from above with the lower part dangling free.",
    example: "\"that's where people are supposed to hang their washing\"" },
  { infinitive: "have", pastSimple: "had", pastParticiple: "had", definition: "possess, own, or hold.", example: "\"he had a new car and a boat\"" },
  { infinitive: "hear", pastSimple: "heard", pastParticiple: "heard", definition: "perceive with the ear the sound made by (someone or something).",
    example: "\"behind her she could hear men's voices\"" },
  { infinitive: "hide", pastSimple: "hid", pastParticiple: "hidden", definition: "put or keep out of sight.", example: "\"he hid the money in the house\"" },
  { infinitive: "hit", pastSimple: "hit", pastParticiple: "hit", definition: "strike with a hand or an object.", example: "\"he hit the ball with his bat\"" },
  { infinitive: "hold", pastSimple: "held", pastParticiple: "held", definition: "grasp, carry, or support with one's hands.",
    example: "\"she was holding a brown leather suitcase\"" },
  { infinitive: "hurt", pastSimple: "hurt", pastParticiple: "hurt", definition: "cause pain or damage to (someone or something).", example: "\"she hurt her knee\"" },
  { infinitive: "keep", pastSimple: "kept", pastParticiple: "kept", definition: "have or retain possession of.", example: "\"he kept the money in his wallet\"" },
  { infinitive: "know", pastSimple: "knew", pastParticiple: "known", definition: "be aware of through observation, inquiry, or information.",
    example: "\"most people know that CFCs can damage the ozone layer\"" },
  { infinitive: "leave", pastSimple: "left", pastParticiple: "left", definition: "go away from.", example: "\"he left the room\"" },
  { infinitive: "lend", pastSimple: "lent", pastParticiple: "lent", definition: "grant to (someone) the use of (something) on the understanding that it will be returned.",
    example: "\"Stewart asked me to lend him my car\"" },
];



// { infinitive: "", pastSimple: "", pastParticiple: "", definition: "", example: "" },